views:
  - cards:
      - type: custom:stack-in-card
        title: Vertical Stack In Card
        cards:
          - type: entities
            title: "Entities"
            entities:
              - light.bed_light
              - light.ceiling_lights
          - type: custom:stack-in-card
            title: Horizontal Stack In Card
            horizontal: true
            cards:
              - type: button
                entity: light.bed_light
              - type: button
                entity: light.ceiling_lights
              - type: button
                entity: light.bed_light
              - type: button
                entity: light.ceiling_lights
      # - type: custom:stack-in-card
      #   title: Horizontal Stack In Card
      #   horizontal: true
      #   cards:
      #     - type: button
      #       entity: light.bed_light
      #     - type: button
      #       entity: light.ceiling_lights
      # - type: custom:vertical-stack-in-card
      #   title: Vertical Stack In Card
      #   cards:
      #     - type: entities
      #       title: "Entities"
      #       entities:
      #         - light.bed_light
      #         - light.ceiling_lights
      #     - type: custom:stack-in-card
      #       title: Horizontal Stack In Card
      #       horizontal: true
      #       cards:
      #         - type: button
      #           entity: light.bed_light
      #         - type: button
      #           entity: light.ceiling_lights
      #         - type: button
      #           entity: light.bed_light
      #         - type: button
      #           entity: light.ceiling_lights
      # - type: custom:vertical-stack-in-card
      #   title: Horizontal Stack In Card
      #   horizontal: true
      #   cards:
      #     - type: button
      #       entity: light.bed_light
      #     - type: button
      #       entity: light.ceiling_lights
      # # - type: vertical-stack
      # #   title: Vertical Stack
      # #   cards:
      # #     - type: entities
      # #       title: "Entities"
      # #       entities:
      # #         - light.bed_light
      # #         - light.ceiling_lights
      # # - type: horizontal-stack
      # #   title: Horizontal Stack
      # #   cards:
      # #     - type: button
      # #       entity: light.bed_light
      # #     - type: button
      # #       entity: light.ceiling_lights
