views:
  - cards:
      - type: entities
        title: "Entities"
        entities:
          - light.bed_light
          - type: divider
          - type: section
            label: lols
          - light.ceiling_lights
          - light.kitchen_lights
          - light.office_rgbw_lights
      - type: custom:stack-in-card
        title: Vertical Stack In Card
        cards:
          - type: custom:stack-in-card
            horizontal: true
            cards:
              - type: button
                entity: light.bed_light
              - type: button
                entity: light.ceiling_lights
              - type: button
                entity: light.kitchen_lights
              - type: button
                entity: light.office_rgbw_lights
          - type: divider
          - type: section
            label: lols
          - type: custom:stack-in-card
            horizontal: true
            cards:
              - type: button
                entity: light.bed_light
              - type: button
                entity: light.ceiling_lights
              - type: button
                entity: light.kitchen_lights
              - type: button
                entity: light.office_rgbw_lights
          - type: divider
          - type: custom:stack-in-card
            horizontal: true
            cards:
              - type: button
                entity: light.bed_light
              - type: button
                entity: light.ceiling_lights
              - type: button
                entity: light.kitchen_lights
              - type: button
                entity: light.office_rgbw_lights

      # ####################
      # No Headings
      # ####################
      - type: custom:stack-in-card
        title: Vertical Stack In Card
        cards:
          - type: entities
            title: "Entities"
            entities:
              - light.bed_light
              - light.ceiling_lights
              - light.kitchen_lights
              - light.office_rgbw_lights
      - type: custom:stack-in-card
        title: Horizontal Stack In Card
        horizontal: true
        cards:
          - type: button
            entity: light.bed_light
          - type: button
            entity: light.ceiling_lights
          - type: button
            entity: light.kitchen_lights
          - type: button
            entity: light.office_rgbw_lights

      # ####################
      # No Headings
      # ####################
      - type: custom:stack-in-card
        cards:
          - type: entities
            title: "Entities"
            entities:
              - light.bed_light
              - light.ceiling_lights
              - light.kitchen_lights
              - light.office_rgbw_lights
      - type: custom:stack-in-card
        horizontal: true
        cards:
          - type: button
            entity: light.bed_light
          - type: button
            entity: light.ceiling_lights
          - type: button
            entity: light.kitchen_lights
          - type: button
            entity: light.office_rgbw_lights
